### ISSUE TITLE
How to specify bakeware as a Mix dependency?

### ISSUE THREAD

**Issue by savonarola** [spawnfest/bakeware#34]
Hello! This project looks really awesome!

But what is the supposed way to use this project? I haven't found it in hex.pm, and `mix.exs` is not in the root, so one can't specify the project as a git mix dependency.

Are there any plans to publish it on hex.pm?

Thank you!

**Comment by fhunleth** [comment]
Yes - we definitely have plans to publish to hex.pm.

I think that if you specify your dep like this, it should work:

```
{:bakeware, github: "spawnfest/bakeware", branch: "main", sparse: "bakeware"}
```

Option 2 would be to clone the repository and use a path dependency. 

The repository is read-only for us until the SpawnFest results are announced. We also need to sleep, but once all that's done, we'll be pushing updates again and straightening out some loose ends.

**Comment by savonarola** [comment]
Thanks a lot. `sparse: "bakeware"` — this was the missing part :)

**Comment by EdBondRSA** [comment]
:+1:  for a hex.pm package soon
