### ISSUE TITLE
Any plans for a bakeware:alpine image for docker?

### ISSUE THREAD

**Issue by Ivor** [spawnfest/bakeware#41]
Having a docker image that has bakeware compiled into it would be great. 
We have the elixir:alpine images but bakeware requires elixir_make and it seems GCC and friends are not installed on alpine. 
I'm not a seasoned docker user but it would be nice to have a docker image that already has bakeware built ontop of alpine. 

Maybe someone is working on that already?

**Comment by smaximov** [comment]
> We have the elixir:alpine images but bakeware requires elixir_make and it seems GCC and friends are not installed on alpine

You can always install additional Alpine packages in Dockerfile:

``` docker
RUN apk add --no-cache \
    gcc \
    musl-dev
```

**Comment by Ivor** [comment]
Definitely in stages. I'm currently building the app on an ubuntu/elixir image so it's easier to install and compile bakeware and then releasing to get the bakeware binary which is then copied over to a an alpine container. 
Main reason is just to make the build process as fast as possible and the final container as small as possible. The build container could be much smaller if I installed the various requirements to compile bakeware on alpine which I have had trouble with. 

If there was an image for bakeware:alpine it would just make that process simpler for others. I didn't understand how to use bakeware when I tried this yesterday, so cloned it into a separate directory next to the app and referenced the right folder. I saw in another issue today I can use the `sparse` option. Maybe that solves most of what I was struggling with. 
I have to be honest I don't grok any of these technologies well enough to really make a strong case or ask intelligent questions.

**Comment by ConnorRigby** [comment]
```dockerfile
FROM erlang:23-alpine as build

ENV ELIXIR_VERSION="v1.10.4-otp-23"

# # install elixir
RUN wget https://repo.hex.pm/builds/elixir/$ELIXIR_VERSION.zip && \
  mkdir -p /usr/local/elixir && \
  unzip -d /usr/local/elixir $ELIXIR_VERSION.zip
ENV PATH=/usr/local/elixir/bin:$PATH

RUN apk add make gcc musl-dev alpine-sdk

RUN mix do local.hex --force, local.rebar --force

FROM build AS compile

WORKDIR /app

ENV MIX_ENV=prod

COPY mix.exs mix.lock ./

COPY bakeware ./

RUN mix do deps.get, deps.compile

# compile and build release
COPY lib lib
RUN mix do compile, release

FROM alpine:latest AS app

RUN apk add --no-cache openssl ncurses-libs
COPY --from=compile --chown=nobody:nobody /app/_build/prod/rel/bakeware/simple_docker /bin
ENV HOME=/app
RUN mkdir -p /app/.cache/
CMD ["/bin/simple_docker"]
```
I just built this and it worked fine. I don't think this is something that the Bakeware team plans on building and maintaining since it's pretty easy to do.
