### ISSUE TITLE
Can't get the project to work with any of the examples on Arch Linux

### ISSUE THREAD

**Issue by jkbbwr** [spawnfest/bakeware#42]
```
jakob@devtank~/p/p/b/e/s/_/p/r/bakeware (main)> ./simple_app 
bakeware: starting '/home/jakob/projects/personal/bakeware/examples/simple_app/_build/prod/rel/bakeware/simple_app' (cachedir=/home/jakob/.cache/bakeware)...
bakeware: Cache invalid. Extracting...
bakeware: CPIO read error? read=0 (wanted 110): File exists
bakeware: CPIO extraction failed.: File exists
bakeware: Unrecoverable validation error
```

```
jakob@devtank~/p/p/b/e/s/_/p/r/bakeware (main)> elixir --version
Erlang/OTP 23 [erts-11.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.10.4 (compiled with Erlang/OTP 23)
```

Using bakeware master. 

```
Linux devtank 5.8.9-arch2-1 #1 SMP PREEMPT Sun, 13 Sep 2020 23:44:55 +0000 x86_64 GNU/Linux```

**Comment by fhunleth** [comment]
Thanks for your report. 

It sounds like something broke in the creation of `./simple_app`. Could you post the `simple_app` binary for us to take a look at? I have a suspicion on what failed, but inspecting the binary would confirm it.

**Comment by jkbbwr** [comment]
https://gofile.io/d/gdHlIo

This is the `sample_app` built on my machine the sha256 for it is 
`4c0129528fb3241f307664b55c05663b3538584dd0fb27c66fcf959e717a58d3`

I cannot vouch for the safety of gofile but it seemed okay.

**Comment by fhunleth** [comment]
Thanks!

I believe that this line failed:
https://github.com/spawnfest/bakeware/blob/main/bakeware/lib/bakeware/assembler.ex#L74

In the rush of the competition, it looks like we totally neglected to even check for a bad error status. That will definitely have to be fixed. 

If you want to continue trying out `bakeware` before we get to fixing it, I'd verify that it is indeed that line that fails. Then I'd take a guess that the problem is either `cpio` or there are spaces in one of the paths (since the paths aren't quoted).

**Comment by jkbbwr** [comment]
Turns out I didn't have `cpio` installed. Good spot. We might want to have some sort of check for if it is installed or not.

Also is there a way to get rid of the bakeware debugging output?

**Comment by fhunleth** [comment]
Comment out this line to turn off debug messages:

https://github.com/spawnfest/bakeware/blob/main/bakeware/src/bakeware.h#L23

The repository is read-only until Spawnfest is over and I don't think that's long off. Once that's over, we'll be resuming work on it or if it takes longer than expected, we'll make a fork and continue from there. There are definitely a few things that if we had time to fix during the competition weekend, we would have. Thanks for your patience on this.

**Comment by jkbbwr** [comment]
I am not in a rush, it looks pretty dope. Have fun at the rest of the event and such.
